global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.18.0.1:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['172.18.0.1:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['172.18.0.1:9121']

  # Add your application services for monitoring
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'  # Update if your app exposes metrics on a different path

  - job_name: 'chat-room'
    static_configs:
      - targets: ['chat-room:8001']
    metrics_path: '/metrics'

  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:9108']
    metrics_path: '/'

  - job_name: 'landing-service'
    static_configs:
      - targets: ['landing-service:8003']
    metrics_path: '/metrics'

